[package]
name = "async-spawner"
version = "1.0.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "executor independent task spawner"
repository = "https://github.com/dvc94ch/async-spawner"

[dependencies]
parking_lot = "0.11.1"

[dev-dependencies]
async-std = { version = "1.7.0", features = ["attributes"] }
tokio = { version = "0.3.4", features = ["macros", "rt-multi-thread"] }
