[package]
name = "agnostic_async_executor"
version = "0.1.0"
authors = ["Pablo Guerrero", "David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Agnostic Rust Async Executor"
repository = "https://github.com/siriux/agnostic_async_executor"

[features]
async_std_executor = ["async-std"]
tokio_executor = ["tokio/rt-multi-thread", "futures/executor"]
smol_executor = ["async-executor", "num_cpus", "async-channel", "blocking", "futures-lite", "easy-parallel"]
futures_executor = ["futures/thread-pool"]
wasm_bindgen_executor = ["wasm-bindgen-futures", "futures/executor"]
time = []
async_std_executor_with_time = ["async_std_executor", "time"]
tokio_executor_with_time = ["tokio_executor", "time", "tokio/time"]
smol_executor_with_time = ["smol_executor", "time", "async-io"]
futures_executor_with_time = ["futures_executor", "time", "async-timer"]
wasm_bindgen_executor_with_time = ["wasm_bindgen_executor", "time", "async-timer"]

[dependencies]
once_cell =  "^1.5"
futures = { version = "^0.3", default-features = false, optional = true }
async-std = { version = "^1.9", features = ["unstable"], optional = true }
tokio = { version = "^1.1", features = ["macros"], optional = true }
async-executor = { version = "^1.4", optional = true }
num_cpus = { version = "^1.13", optional = true }
async-channel = { version = "^1.5", optional = true }
easy-parallel = { version = "^3.1", optional = true }
blocking = { version = "^1.0", optional = true }
futures-lite = { version = "^1.11", optional = true }
wasm-bindgen-futures = { version = "^0.4", optional = true }
async-io = { version = "^1.3", optional = true }
async-timer = { version = "1.0.0-beta.7", optional = true }

[dev-dependencies]
# This needs to be commented to run the wasm tests, uncomment it for easier development and simple cargo test (this might change when this is fixed https://github.com/rustwasm/wasm-pack/issues/698)
agnostic_async_executor = { path = ".", features = ["async_std_executor_with_time", "tokio_executor_with_time", "smol_executor_with_time", "futures_executor_with_time"] }

[target.wasm32-unknown-unknown.dev-dependencies]
agnostic_async_executor = { path = ".", features = ["wasm_bindgen_executor_with_time"] }
wasm-bindgen-test = "^0.3"
wasm-bindgen = "^0.2.7"