[package]
name = "agnostic_async_executor"
version = "0.1.0"
authors = ["Pablo Guerrero", "David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Agnostic Rust Async Executor"
repository = "https://github.com/siriux/agnostic_async_executor"

[features]
asyncstd_executor = ["async-std"]
tokio_mt_executor = ["tokio/rt-multi-thread"]
tokio_ct_executor = ["tokio/rt"]
#smol_executor = ["smol"]

[dependencies]
futures-util = { version = "0.3.12", default-features = false }
futures-channel = { version = "0.3.12", default-features = false }
async-std = { version = "1.9.0", features = ["attributes"], optional = true }
tokio = { version = "1.1.0", features = ["macros"], optional = true }

[dev-dependencies]
agnostic_async_executor = { path = ".", features = ["asyncstd_executor", "tokio_mt_executor", "tokio_ct_executor"] }
async-std = { version = "1.9.0", features = ["attributes", "unstable"] }
tokio = { version = "1.1.0", features = ["macros", "rt-multi-thread"] }
