[package]
name = "async-spawner"
version = "2.0.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "executor independent task spawner"
repository = "https://github.com/dvc94ch/async-spawner"

[dependencies]
futures = "0.3.8"
once_cell = "1.5.2"
bumpalo = { version = "3.4.0", features = ["boxed"] }

[dev-dependencies]
async-std = { version = "1.7.0", features = ["attributes", "unstable"] }
tokio = { version = "0.3.4", features = ["macros", "rt-multi-thread"] }
